name: Weekly Release WRT
run-name: Weekly Release WRT

on:
  # schedule:
  #   - cron: "0 4 * * 5"
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write

jobs:
  release:
    name: Release ${{ matrix.model }}
    strategy:
      fail-fast: false
      matrix:
        model:
          
          - lk_ipq60xx_libwrt
          - lk_ipq60xx_libwrt_mini

    uses: ./.github/workflows/release_wrt.yml
    with:
      model: ${{ matrix.model }}
    secrets: inherit
